name: Deploy to Firebase Hosting on main push

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Version plus récente

      - name: Install Dependencies
        run: npm ci # Installe vos packages proprement

      - name: Build Project
        run: npm run build # Génère le dossier 'dist' ou 'build'

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ECO_GESTION_D764E }}'
          channelId: live
          projectId: eco-gestion-d764e